
-----7.1.1----
create FUNCTION FN_TUOI(@MANV NVARCHAR (9))
RETURNS INT
AS
BEGIN
 RETURN(
  SELECT DATEDIFF(YEAR,NGSINH,GETDATE()) +1 FROM NHANVIEN WHERE MANV = @MANV
 );
 END;

 SELECT [dbo].[FN_TUOI](005);

 ---7.1.2---
 create FUNCTION FN_TONGSODEAN (@MANV NVARCHAR (9))
 RETURNS INT
AS
BEGIN
 RETURN(
  SELECT COUNT(MADA) FROM PHANCONG WHERE MA_NVIEN= @MANV
 );
 END;


 SELECT [dbo].[FN_TONGSODEAN](005);

 ----7.1.3---
 create FUNCTION FN_THONGKEPHAI (@PHAI NVARCHAR (9))
 RETURNS INT
AS
BEGIN
 RETURN(
  SELECT COUNT(MANV) FROM NHANVIEN WHERE PHAI= @PHAI
 );
 END;


 SELECT [dbo].[FN_THONGKEPHAI](N'NỮ');
 ---7.1.4---
 create FUNCTION FN_LUONGLB (@TENPHONG NVARCHAR (30))
 RETURNS INT
AS
BEGIN
 RETURN(
  SELECT AVG(B.LUONG) FROM PHONGBAN A INNER JOIN NHANVIEN B ON A.MAPHG =B.PHG 
  WHERE TENPHG LIKE '%' + @TENPHONG +'%'
 );
 END;


 SELECT HONV,TENLOT, TENNV FROM NHANVIEN A INNER JOIN PHONGBAN B ON A.PHG = B.MAPHG
 WHERE LUONG>[dbo].[FN_LUONGLB](N'QUAN LY') AND TENPHG LIKE N'%QUANLY%';

--- 7.1.5---
CREATE FUNCTION FN_THONGTINPHONGDEAN 
(@MAPHG INT)
 RETURNS @LIST TABLE (TENPHONG NVARCHAR(15),TENTRUONGPHONG NVARCHAR(30), SOLUONGDEAN INT)
AS
BEGIN
INSERT INTO @LIST
 SELECT A.TENPHG, B.HONV +' '+ B.TENLOT +' '+B.TENNV,
 (SELECT COUNT(C.MADA) FROM DEAN C WHERE C.PHONG = A.MAPHG)
 FROM PHONGBAN A INNER JOIN NHANVIEN B ON A.MAPHG =B.PHG
 RETURN;
 END;


 
SELECT * FROM [dbo].[FN_THONGTINPHONGDEAN](1);

---7.2.1---
select HONV,TENPHG,DIADIEM from PHONGBAN
inner join DIADIEM_PHG on DIADIEM_PHG.MAPHG = PHONGBAN.MAPHG
inner join NHANVIEN on NHANVIEN.PHG = PHONGBAN.MAPHG

create view f_DD_PhongBan
as
select HONV,TENPHG,DIADIEM from PHONGBAN
inner join DIADIEM_PHG on DIADIEM_PHG.MAPHG = PHONGBAN.MAPHG
inner join NHANVIEN on NHANVIEN.PHG = PHONGBAN.MAPHG

select * from f_DD_PhongBan

---7.2.2----
select TENNV,LUONG,YEAR(GETDATE())-YEAR(NGSINH)as 'Tuoi' from NHANVIEN

create view f_TuoiNV
as
select TENNV,LUONG,YEAR(GETDATE())-YEAR(NGSINH)as 'Tuoi' from NHANVIEN

select * from f_TuoiNV

---7.2.3---
select top(1) TENPHG,TRPHG,B.HONV+' '+B.TENLOT+' '+B.TENNV as 'TenTP',COUNT(A.MANV)as 'SoLuongNV' from NHANVIEN A
inner join PHONGBAN on PHONGBAN.MAPHG = A.PHG
inner join NHANVIEN B on B.MANV = PHONGBAN.TRPHG
group by TENPHG,TRPHG,B.TENNV,B.HONV,B.TENLOT
order by SoLuongNV desc

create view f_TopSoLuongNV_PB
as
select top(1) TENPHG,TRPHG,B.HONV+' '+B.TENLOT+' '+B.TENNV as 'TenTP',COUNT(A.MANV)as 'SoLuongNV' 
from NHANVIEN A
inner join PHONGBAN on PHONGBAN.MAPHG = A.PHG
inner join NHANVIEN B on B.MANV = PHONGBAN.TRPHG
group by TENPHG,TRPHG,B.TENNV,B.HONV,B.TENLOT
order by SoLuongNV desc

select * from f_TopSoLuongNV_PB